#cloud-config
repo_update: true
repo_upgrade: all

debug:
  verbose: true

packages:
  - git
  - git-core
  - zip
  - unzip

runcmd:
#  - [wget, "https://github.com/matthewzimmer/carnd-keras-lab/archive/master.zip", -O, ~/carnd-keras-lab.zip]
  - git clone https://github.com/matthewzimmer/carnd-keras-lab.git
  - git clone https://github.com/matthewzimmer/carnd-transfer-learning.git
  - git clone https://github.com/matthewzimmer/carnd-behavioral-cloning.git




write_files:
- content: |
    #! /bin/bash
    cd ~/carnd-keras-lab && git pull
    cd ~/carnd-transfer-learning && git pull
    cd ~/carnd-behavioral-cloning && git pull
    exit 0
  owner: carnd:carnd
  path: ~/git-pull.sh
  permissions: '0755'

# final_message
# default: cloud-init boot finished at $TIMESTAMP. Up $UPTIME seconds
# this message is written by cloud-final when the system is finished
# its first boot
final_message: "The system is ready, after $UPTIME seconds"